// Code generated by protoc-gen-go. DO NOT EDIT.
// source: language-agent-v2/CLRMetric.proto

package language_agent_v2

import (
	context "context"
	fmt "fmt"
	common "github.com/SkyAPM/go2sky/reporter/grpc/common"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CLRMetricCollection struct {
	Metrics              []*common.CLRMetric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	ServiceInstanceId    int32               `protobuf:"varint,2,opt,name=serviceInstanceId,proto3" json:"serviceInstanceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CLRMetricCollection) Reset()         { *m = CLRMetricCollection{} }
func (m *CLRMetricCollection) String() string { return proto.CompactTextString(m) }
func (*CLRMetricCollection) ProtoMessage()    {}
func (*CLRMetricCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f032372dea03c68, []int{0}
}

func (m *CLRMetricCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLRMetricCollection.Unmarshal(m, b)
}
func (m *CLRMetricCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLRMetricCollection.Marshal(b, m, deterministic)
}
func (m *CLRMetricCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLRMetricCollection.Merge(m, src)
}
func (m *CLRMetricCollection) XXX_Size() int {
	return xxx_messageInfo_CLRMetricCollection.Size(m)
}
func (m *CLRMetricCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_CLRMetricCollection.DiscardUnknown(m)
}

var xxx_messageInfo_CLRMetricCollection proto.InternalMessageInfo

func (m *CLRMetricCollection) GetMetrics() []*common.CLRMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *CLRMetricCollection) GetServiceInstanceId() int32 {
	if m != nil {
		return m.ServiceInstanceId
	}
	return 0
}

func init() {
	proto.RegisterType((*CLRMetricCollection)(nil), "CLRMetricCollection")
}

func init() { proto.RegisterFile("language-agent-v2/CLRMetric.proto", fileDescriptor_1f032372dea03c68) }

var fileDescriptor_1f032372dea03c68 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xed, 0x44, 0x87, 0xf1, 0xa2, 0x9d, 0xc8, 0xd8, 0x69, 0x0e, 0x0f, 0x3b, 0x6c, 0x09,
	0x74, 0x67, 0x2f, 0x16, 0x84, 0xc1, 0x94, 0xd1, 0x1d, 0x04, 0x6f, 0x59, 0xf6, 0xc8, 0x42, 0x93,
	0xbc, 0x92, 0x64, 0x1d, 0xfd, 0x1c, 0x7e, 0x0b, 0x3f, 0xa5, 0xac, 0xed, 0xe6, 0x61, 0x9e, 0x02,
	0xbf, 0xf7, 0xf2, 0xfe, 0x7f, 0x7e, 0xe4, 0x49, 0x73, 0x2b, 0x77, 0x5c, 0xc2, 0x94, 0x4b, 0xb0,
	0x61, 0x5a, 0x26, 0x2c, 0x5d, 0x64, 0xef, 0x10, 0x9c, 0x12, 0xb4, 0x70, 0x18, 0x70, 0xd0, 0x13,
	0x68, 0x0c, 0x5a, 0xd6, 0x3c, 0x2d, 0xbc, 0x6b, 0x61, 0xba, 0xc8, 0x1a, 0x32, 0x52, 0xa4, 0x77,
	0xfa, 0x99, 0xa2, 0xd6, 0x20, 0x82, 0x42, 0x1b, 0x3f, 0x93, 0xae, 0xa9, 0x99, 0xef, 0x47, 0xc3,
	0xcb, 0xf1, 0x6d, 0x42, 0xe8, 0x69, 0x2d, 0x3b, 0x8e, 0xe2, 0x09, 0xb9, 0xf7, 0xe0, 0x4a, 0x25,
	0x60, 0x6e, 0x7d, 0xe0, 0x56, 0xc0, 0x7c, 0xd3, 0xef, 0x0c, 0xa3, 0xf1, 0x55, 0x76, 0x3e, 0x48,
	0xde, 0xc8, 0xe3, 0xdf, 0x0d, 0x28, 0xd0, 0x85, 0x55, 0xb3, 0x13, 0x4f, 0x48, 0x57, 0x34, 0xd9,
	0xf1, 0x03, 0xfd, 0xa7, 0xce, 0xe0, 0x86, 0xa6, 0x68, 0x0c, 0xb7, 0x1b, 0x3f, 0xba, 0x78, 0xfd,
	0x8e, 0xc8, 0x0c, 0x9d, 0xa4, 0xbc, 0xe0, 0x62, 0x0b, 0xd4, 0xe7, 0xd5, 0x9e, 0xeb, 0x5c, 0xd9,
	0x03, 0x31, 0xd4, 0x42, 0xd8, 0xa3, 0xcb, 0xe9, 0xd1, 0x10, 0xad, 0x0d, 0xd1, 0x32, 0x59, 0x46,
	0x5f, 0x2f, 0x52, 0x85, 0xed, 0x6e, 0x4d, 0x05, 0x1a, 0x16, 0x20, 0x38, 0x1e, 0x40, 0xf3, 0xb5,
	0x67, 0x12, 0x13, 0x9f, 0x57, 0xcc, 0xd5, 0xa5, 0xc0, 0x31, 0xe9, 0x0a, 0xc1, 0xce, 0x14, 0xff,
	0x74, 0x06, 0xab, 0xbc, 0xfa, 0x6c, 0xb3, 0x3e, 0x9a, 0x9c, 0xe5, 0xc1, 0xa2, 0x40, 0xbd, 0xbe,
	0xae, 0x7d, 0xce, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x22, 0xbf, 0x24, 0x9b, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CLRMetricReportServiceClient is the client API for CLRMetricReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CLRMetricReportServiceClient interface {
	Collect(ctx context.Context, in *CLRMetricCollection, opts ...grpc.CallOption) (*common.Commands, error)
}

type cLRMetricReportServiceClient struct {
	cc *grpc.ClientConn
}

func NewCLRMetricReportServiceClient(cc *grpc.ClientConn) CLRMetricReportServiceClient {
	return &cLRMetricReportServiceClient{cc}
}

func (c *cLRMetricReportServiceClient) Collect(ctx context.Context, in *CLRMetricCollection, opts ...grpc.CallOption) (*common.Commands, error) {
	out := new(common.Commands)
	err := c.cc.Invoke(ctx, "/CLRMetricReportService/collect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CLRMetricReportServiceServer is the server API for CLRMetricReportService service.
type CLRMetricReportServiceServer interface {
	Collect(context.Context, *CLRMetricCollection) (*common.Commands, error)
}

// UnimplementedCLRMetricReportServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCLRMetricReportServiceServer struct {
}

func (*UnimplementedCLRMetricReportServiceServer) Collect(ctx context.Context, req *CLRMetricCollection) (*common.Commands, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Collect not implemented")
}

func RegisterCLRMetricReportServiceServer(s *grpc.Server, srv CLRMetricReportServiceServer) {
	s.RegisterService(&_CLRMetricReportService_serviceDesc, srv)
}

func _CLRMetricReportService_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CLRMetricCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLRMetricReportServiceServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLRMetricReportService/Collect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLRMetricReportServiceServer).Collect(ctx, req.(*CLRMetricCollection))
	}
	return interceptor(ctx, in, info, handler)
}

var _CLRMetricReportService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CLRMetricReportService",
	HandlerType: (*CLRMetricReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "collect",
			Handler:    _CLRMetricReportService_Collect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "language-agent-v2/CLRMetric.proto",
}
